// pi-ai built-in model catalog for deepseek provider.
// 2026-09-07 teyvat override：官方 built-in catalog（auto-generated by scripts/generate-models.ts）只有
// deepseek-v4-flash / deepseek-v4-pro 两个，缺 vision 模型。teyvat 经此 override 加 deepseek-v4-flash-vision-exp
// （多模态视觉，input 含 "image"）——随 make 发布到所有电脑，/m 里 deepseek 即 pro/flash/vision-exp 三个官方模型。
// 注：本文件是 pi 官方 deepseek.models.js 的 teyvat 定制版（官方 + vision-exp），发布走 install.sh 的 pi-ai override。
export const DEEPSEEK_MODELS = {
    "deepseek-v4-flash": {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        api: "openai-completions",
        provider: "deepseek",
        baseUrl: "https://api.deepseek.com",
        compat: { "supportsStore": false, "supportsDeveloperRole": false, "requiresReasoningContentOnAssistantMessages": true, "thinkingFormat": "deepseek" },
        reasoning: true,
        thinkingLevelMap: { "minimal": null, "low": null, "medium": null, "high": "high", "max": "max" },
        input: ["text"],
        cost: {
            input: 0.14,
            output: 0.28,
            cacheRead: 0.0028,
            cacheWrite: 0,
        },
        contextWindow: 1000000,
        maxTokens: 384000,
    },
    "deepseek-v4-flash-vision-exp": {
        id: "deepseek-v4-flash-vision-exp",
        name: "DeepSeek V4 Flash Vision Exp",
        api: "openai-completions",
        provider: "deepseek",
        baseUrl: "https://api.deepseek.com",
        compat: { "supportsStore": false, "supportsDeveloperRole": false, "requiresReasoningContentOnAssistantMessages": true, "thinkingFormat": "deepseek" },
        reasoning: true,
        thinkingLevelMap: { "minimal": null, "low": null, "medium": null, "high": "high", "max": "max" },
        input: ["text", "image"],
        cost: {
            input: 0.14,
            output: 0.28,
            cacheRead: 0.0028,
            cacheWrite: 0,
        },
        contextWindow: 1000000,
        maxTokens: 384000,
    },
    "deepseek-v4-pro": {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        api: "openai-completions",
        provider: "deepseek",
        baseUrl: "https://api.deepseek.com",
        compat: { "supportsStore": false, "supportsDeveloperRole": false, "requiresReasoningContentOnAssistantMessages": true, "thinkingFormat": "deepseek" },
        reasoning: true,
        thinkingLevelMap: { "minimal": null, "low": null, "medium": null, "high": "high", "max": "max" },
        input: ["text"],
        cost: {
            input: 0.435,
            output: 0.87,
            cacheRead: 0.003625,
            cacheWrite: 0,
        },
        contextWindow: 1000000,
        maxTokens: 384000,
    },
};
