// apps/calendar/calendar.ts — Calendar app
// v0.2 spec: 日历 — 日程管理、提醒、查询
// "记录、查看、会有提醒日程等"
// v0.3: 集成节假日日历 (根据 Settings 地区自动加载)
// v0.4: 合并 holiday-calendar.ts — 节假日数据 + 阴历换算
//   Apple Calendar 级别的中美节假日，支持阴历节日
//   Lunar data: 1901-2099, auto-generated by cnlunar (196 years)
//   Leap months handled correctly via leapIdx

import * as fs from "fs";
import * as path from "path";

// ── Region ────────────────────────────────────────────────────
export type Region = "CN" | "US";

export function getRegion(personDir: string): Region {
  try {
    const raw = JSON.parse(fs.readFileSync(path.join(personDir, "settings.json"), "utf8"));
    return raw.region === "US" ? "US" : "CN";
  } catch (e) { console.error("[universe.infotech/local.mobile/apps/calendar/calendar.ts] " + ((e as any)?.message || e));
    return "CN";
  }
}

export function setRegion(personDir: string, region: Region) {
  let settings: any = {};
  try {
    settings = JSON.parse(fs.readFileSync(path.join(personDir, "settings.json"), "utf8"));
  } catch (e) { console.error("[universe.infotech/local.mobile/apps/calendar/calendar.ts] " + ((e as any)?.message || e)); }
  settings.region = region;
  fs.writeFileSync(path.join(personDir, "settings.json"), JSON.stringify(settings, null, 2));
}

// ── Holiday type ──────────────────────────────────────────────
export interface Holiday {
  date: string;       // YYYY-MM-DD
  name: string;
  emoji: string;
  type: "public" | "observance" | "traditional";
  lunar?: string;
}

// ── Helpers ───────────────────────────────────────────────────
function fmtLocal(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}
function nthWeekdayOf(year: number, month: number, weekday: number, n: number): string {
  const d = new Date(year, month - 1, 1);
  while (d.getDay() !== weekday) d.setDate(d.getDate() + 1);
  d.setDate(d.getDate() + (n - 1) * 7);
  return fmtLocal(d);
}
function lastWeekdayOf(year: number, month: number, weekday: number): string {
  const d = new Date(year, month, 0);
  while (d.getDay() !== weekday) d.setDate(d.getDate() - 1);
  return fmtLocal(d);
}

// ── US Holidays (Federal + observances, matching Apple Calendar) ──
function usHolidays(year: number): Holiday[] {
  const h: Holiday[] = [
    { date: `${year}-01-01`, name: "New Year's Day", emoji: "", type: "public" },
    { date: nthWeekdayOf(year, 1, 1, 3), name: "Martin Luther King Jr. Day", emoji: "", type: "public" },
    { date: nthWeekdayOf(year, 2, 1, 3), name: "Presidents' Day", emoji: "", type: "public" },
    { date: lastWeekdayOf(year, 5, 1), name: "Memorial Day", emoji: "", type: "public" },
    { date: `${year}-06-19`, name: "Juneteenth", emoji: "", type: "public" },
    { date: `${year}-07-04`, name: "Independence Day", emoji: "", type: "public" },
    { date: nthWeekdayOf(year, 9, 1, 1), name: "Labor Day", emoji: "", type: "public" },
    { date: nthWeekdayOf(year, 10, 1, 2), name: "Columbus Day", emoji: "", type: "public" },
    { date: `${year}-11-11`, name: "Veterans Day", emoji: "", type: "public" },
    { date: nthWeekdayOf(year, 11, 4, 4), name: "Thanksgiving", emoji: "", type: "public" },
    { date: `${year}-12-25`, name: "Christmas Day", emoji: "", type: "public" },
  ];
  h.push(
    { date: `${year}-02-14`, name: "Valentine's Day", emoji: "", type: "observance" },
    { date: `${year}-03-17`, name: "St. Patrick's Day", emoji: "", type: "observance" },
    { date: `${year}-10-31`, name: "Halloween", emoji: "", type: "observance" },
    { date: `${year}-12-24`, name: "Christmas Eve", emoji: "", type: "observance" },
    { date: `${year}-12-31`, name: "New Year's Eve", emoji: "", type: "observance" },
  );
  // Easter (Gauss algorithm)
  const a = year % 19, b = Math.floor(year / 100), c = year % 100;
  const d = Math.floor(b / 4), e = b % 4, f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const hh = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4), k = c % 4;
  const l = (32 + 2 * e + 2 * i - hh - k) % 7;
  const m = Math.floor((a + 11 * hh + 22 * l) / 451);
  const mo = Math.floor((hh + l - 7 * m + 114) / 31);
  const da = ((hh + l - 7 * m + 114) % 31) + 1;
  const easter = `${year}-${String(mo).padStart(2, "0")}-${String(da).padStart(2, "0")}`;
  h.push({ date: easter, name: "Easter", emoji: "", type: "observance" });
  const ed = new Date(easter + "T00:00:00");
  ed.setDate(ed.getDate() - 2);
  h.push({ date: fmtLocal(ed), name: "Good Friday", emoji: "", type: "observance" });
  h.push({ date: nthWeekdayOf(year, 5, 0, 2), name: "Mother's Day", emoji: "", type: "observance" });
  h.push({ date: nthWeekdayOf(year, 6, 0, 3), name: "Father's Day", emoji: "", type: "observance" });
  return h;
}

// ── Lunar calendar data (1901-2099) ──────────────────────────
// cny: Chinese New Year solar date
// leapIdx: 0-based index of leap month (null if none)
// lengths: 12 (normal) or 13 (leap) entries of 29 or 30 days

const LUNAR_DATA: Record<number, {
  cny: string;
  leapIdx: number | null;
  lengths: number[];
}> = {
  1901: { cny: '1901-02-19', leapIdx: null, lengths: [29,30,29,29,30,29,30,29,30,30,30,29] },
  1902: { cny: '1902-02-08', leapIdx: null, lengths: [30,29,30,29,29,30,29,30,29,30,30,30] },
  1903: { cny: '1903-01-29', leapIdx: 4, lengths: [29,30,29,30,29,29,30,29,29,30,30,29,30] },
  1904: { cny: '1904-02-16', leapIdx: null, lengths: [30,30,29,30,29,29,30,29,29,30,30,29] },
  1905: { cny: '1905-02-04', leapIdx: null, lengths: [30,30,29,30,30,29,29,30,29,30,29,30] },
  1906: { cny: '1906-01-25', leapIdx: 3, lengths: [29,30,30,29,30,29,30,29,30,29,30,29,30] },
  1907: { cny: '1907-02-13', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,29,30,29] },
  1908: { cny: '1908-02-02', leapIdx: null, lengths: [30,29,29,30,30,29,30,29,30,30,29,30] },
  1909: { cny: '1909-01-22', leapIdx: 1, lengths: [29,30,29,29,30,29,30,29,30,30,30,29,30] },
  1910: { cny: '1910-02-10', leapIdx: null, lengths: [29,30,29,29,30,29,30,29,30,30,30,29] },
  1911: { cny: '1911-01-30', leapIdx: 5, lengths: [30,29,30,29,29,30,29,29,30,30,29,30,30] },
  1912: { cny: '1912-02-18', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,30,29,30] },
  1913: { cny: '1913-02-06', leapIdx: null, lengths: [30,30,29,30,29,29,30,29,29,30,29,30] },
  1914: { cny: '1914-01-26', leapIdx: 4, lengths: [30,30,29,30,29,30,29,30,29,29,30,29,30] },
  1915: { cny: '1915-02-14', leapIdx: null, lengths: [30,29,30,30,29,30,29,30,29,30,29,29] },
  1916: { cny: '1916-02-03', leapIdx: null, lengths: [30,30,29,30,29,30,30,29,30,29,30,29] },
  1917: { cny: '1917-01-23', leapIdx: 1, lengths: [30,29,29,30,29,30,30,29,30,30,29,30,29] },
  1918: { cny: '1918-02-11', leapIdx: null, lengths: [30,29,29,30,29,30,29,30,30,29,30,30] },
  1919: { cny: '1919-02-01', leapIdx: 6, lengths: [29,30,29,29,30,29,29,30,30,29,30,30,30] },
  1920: { cny: '1920-02-20', leapIdx: null, lengths: [29,30,29,29,30,29,29,30,29,30,30,30] },
  1921: { cny: '1921-02-08', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,29,30,30] },
  1922: { cny: '1922-01-28', leapIdx: 4, lengths: [30,29,30,30,29,29,30,29,29,30,29,30,30] },
  1923: { cny: '1923-02-16', leapIdx: null, lengths: [29,30,30,29,30,29,30,29,29,30,29,30] },
  1924: { cny: '1924-02-05', leapIdx: null, lengths: [29,30,30,29,30,30,29,30,29,30,29,29] },
  1925: { cny: '1925-01-24', leapIdx: 3, lengths: [30,29,30,29,30,30,29,30,30,29,30,29,30] },
  1926: { cny: '1926-02-13', leapIdx: null, lengths: [29,29,30,29,30,29,30,30,29,30,30,29] },
  1927: { cny: '1927-02-02', leapIdx: null, lengths: [30,29,29,30,29,30,29,30,29,30,30,30] },
  1928: { cny: '1928-01-23', leapIdx: 1, lengths: [29,30,29,29,30,29,29,30,29,30,30,30,30] },
  1929: { cny: '1929-02-10', leapIdx: null, lengths: [29,30,29,29,30,29,29,30,29,30,30,30] },
  1930: { cny: '1930-01-30', leapIdx: 5, lengths: [29,30,30,29,29,30,29,29,30,29,30,30,29] },
  1931: { cny: '1931-02-17', leapIdx: null, lengths: [30,30,29,30,29,30,29,29,30,29,30,29] },
  1932: { cny: '1932-02-06', leapIdx: null, lengths: [30,30,30,29,30,29,30,29,29,30,29,30] },
  1933: { cny: '1933-01-26', leapIdx: 4, lengths: [29,30,30,29,30,30,29,30,29,30,29,29,30] },
  1934: { cny: '1934-02-14', leapIdx: null, lengths: [29,30,29,30,30,29,30,29,30,30,29,30] },
  1935: { cny: '1935-02-04', leapIdx: null, lengths: [29,29,30,29,30,29,30,30,29,30,30,29] },
  1936: { cny: '1936-01-24', leapIdx: 2, lengths: [30,29,29,30,29,29,30,30,29,30,30,30,29] },
  1937: { cny: '1937-02-11', leapIdx: null, lengths: [30,29,29,30,29,29,30,29,30,30,30,29] },
  1938: { cny: '1938-01-31', leapIdx: 6, lengths: [30,30,29,29,30,29,29,30,29,30,30,29,30] },
  1939: { cny: '1939-02-19', leapIdx: null, lengths: [30,30,29,29,30,29,29,30,29,30,29,30] },
  1940: { cny: '1940-02-08', leapIdx: null, lengths: [30,30,29,30,29,30,29,29,30,29,30,29] },
  1941: { cny: '1941-01-27', leapIdx: 5, lengths: [30,30,29,30,30,29,30,29,29,30,29,30,29] },
  1942: { cny: '1942-02-15', leapIdx: null, lengths: [30,29,30,30,29,30,29,30,29,30,29,30] },
  1943: { cny: '1943-02-05', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,29,30,29] },
  1944: { cny: '1944-01-25', leapIdx: 3, lengths: [30,29,30,29,30,29,30,29,30,30,29,30,30] },
  1945: { cny: '1945-02-13', leapIdx: null, lengths: [29,29,30,29,29,30,29,30,30,30,29,30] },
  1946: { cny: '1946-02-02', leapIdx: null, lengths: [30,29,29,30,29,29,30,29,30,30,29,30] },
  1947: { cny: '1947-01-22', leapIdx: 1, lengths: [30,30,29,29,30,29,29,30,29,30,29,30,30] },
  1948: { cny: '1948-02-10', leapIdx: null, lengths: [30,29,30,29,30,29,29,30,29,30,29,30] },
  1949: { cny: '1949-01-29', leapIdx: 6, lengths: [30,29,30,30,29,30,29,29,30,29,30,29,30] },
  1950: { cny: '1950-02-17', leapIdx: null, lengths: [29,30,30,29,30,30,29,29,30,29,30,29] },
  1951: { cny: '1951-02-06', leapIdx: null, lengths: [30,29,30,30,29,30,29,30,29,30,29,30] },
  1952: { cny: '1952-01-27', leapIdx: 4, lengths: [29,30,29,30,29,30,29,30,30,29,30,29,30] },
  1953: { cny: '1953-02-14', leapIdx: null, lengths: [29,30,29,29,30,30,29,30,30,29,30,29] },
  1954: { cny: '1954-02-03', leapIdx: null, lengths: [30,29,30,29,29,30,29,30,30,29,30,30] },
  1955: { cny: '1955-01-24', leapIdx: 2, lengths: [29,30,29,30,29,29,30,29,30,29,30,30,30] },
  1956: { cny: '1956-02-12', leapIdx: null, lengths: [29,30,29,30,29,29,30,29,30,29,30,30] },
  1957: { cny: '1957-01-31', leapIdx: 7, lengths: [30,29,30,29,30,29,29,30,29,30,29,30,29] },
  1958: { cny: '1958-02-18', leapIdx: null, lengths: [30,30,30,29,30,29,29,30,29,30,29,30] },
  1959: { cny: '1959-02-08', leapIdx: null, lengths: [29,30,30,29,30,29,30,29,30,29,30,29] },
  1960: { cny: '1960-01-28', leapIdx: 5, lengths: [30,29,30,29,30,30,29,30,29,30,29,30,29] },
  1961: { cny: '1961-02-15', leapIdx: null, lengths: [30,29,30,29,30,29,30,30,29,30,29,30] },
  1962: { cny: '1962-02-05', leapIdx: null, lengths: [29,30,29,29,30,29,30,30,29,30,30,29] },
  1963: { cny: '1963-01-25', leapIdx: 3, lengths: [30,29,30,29,29,30,29,30,29,30,30,30,29] },
  1964: { cny: '1964-02-13', leapIdx: null, lengths: [30,29,30,29,29,30,29,30,29,30,30,30] },
  1965: { cny: '1965-02-02', leapIdx: null, lengths: [29,30,29,30,29,29,30,29,29,30,30,29] },
  1966: { cny: '1966-01-21', leapIdx: 2, lengths: [30,30,30,29,30,29,29,30,29,29,30,30,29] },
  1967: { cny: '1967-02-09', leapIdx: null, lengths: [30,30,29,30,30,29,29,30,29,30,29,30] },
  1968: { cny: '1968-01-30', leapIdx: 6, lengths: [29,30,29,30,30,29,30,29,30,29,30,29,30] },
  1969: { cny: '1969-02-17', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,29,30,29] },
  1970: { cny: '1970-02-06', leapIdx: null, lengths: [30,29,29,30,29,30,30,29,30,30,29,30] },
  1971: { cny: '1971-01-27', leapIdx: 4, lengths: [29,30,29,29,30,29,30,29,30,30,30,29,30] },
  1972: { cny: '1972-02-15', leapIdx: null, lengths: [29,30,29,29,30,29,30,29,30,30,29,30] },
  1973: { cny: '1973-02-03', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,30,29,30] },
  1974: { cny: '1974-01-23', leapIdx: 3, lengths: [30,30,29,30,29,29,30,29,29,30,30,29,30] },
  1975: { cny: '1975-02-11', leapIdx: null, lengths: [30,30,29,30,29,29,30,29,29,30,29,30] },
  1976: { cny: '1976-01-31', leapIdx: 7, lengths: [30,30,29,30,29,30,29,30,29,29,30,29,30] },
  1977: { cny: '1977-02-18', leapIdx: null, lengths: [30,29,30,30,29,30,29,30,29,30,29,29] },
  1978: { cny: '1978-02-07', leapIdx: null, lengths: [30,29,30,30,29,30,30,29,30,29,30,29] },
  1979: { cny: '1979-01-28', leapIdx: 5, lengths: [30,29,29,30,29,30,30,29,30,30,29,30,29] },
  1980: { cny: '1980-02-16', leapIdx: null, lengths: [30,29,29,30,29,30,29,30,30,29,30,30] },
  1981: { cny: '1981-02-05', leapIdx: null, lengths: [29,30,29,29,30,29,29,30,30,29,30,30] },
  1982: { cny: '1982-01-25', leapIdx: 3, lengths: [30,29,30,29,29,30,29,29,30,29,30,30,30] },
  1983: { cny: '1983-02-13', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,29,30,30] },
  1984: { cny: '1984-02-02', leapIdx: 9, lengths: [30,29,30,30,29,29,30,29,29,30,29,30,30] },
  1985: { cny: '1985-02-20', leapIdx: null, lengths: [29,30,30,29,30,29,30,29,29,30,29,30] },
  1986: { cny: '1986-02-09', leapIdx: null, lengths: [29,30,30,29,30,30,29,30,29,30,29,29] },
  1987: { cny: '1987-01-29', leapIdx: 5, lengths: [30,29,30,29,30,30,29,30,30,29,30,29,29] },
  1988: { cny: '1988-02-17', leapIdx: null, lengths: [30,29,30,29,30,29,30,30,29,30,30,29] },
  1989: { cny: '1989-02-06', leapIdx: null, lengths: [30,29,29,30,29,30,29,30,29,30,30,30] },
  1990: { cny: '1990-01-27', leapIdx: 4, lengths: [29,30,29,29,30,29,29,30,29,30,30,30,30] },
  1991: { cny: '1991-02-15', leapIdx: null, lengths: [29,30,29,29,30,29,29,30,29,30,30,30] },
  1992: { cny: '1992-02-04', leapIdx: null, lengths: [29,30,30,29,29,30,29,29,30,29,30,30] },
  1993: { cny: '1993-01-23', leapIdx: 2, lengths: [29,30,30,29,30,29,30,29,29,30,29,30,29] },
  1994: { cny: '1994-02-10', leapIdx: null, lengths: [30,30,30,29,30,29,30,29,29,30,29,30] },
  1995: { cny: '1995-01-31', leapIdx: 7, lengths: [29,30,30,29,30,29,30,30,29,29,30,29,30] },
  1996: { cny: '1996-02-19', leapIdx: null, lengths: [29,30,29,30,30,29,30,29,30,30,29,29] },
  1997: { cny: '1997-02-07', leapIdx: null, lengths: [30,29,30,29,30,29,30,30,29,30,30,29] },
  1998: { cny: '1998-01-28', leapIdx: 4, lengths: [30,29,29,30,29,29,30,30,29,30,30,29,30] },
  1999: { cny: '1999-02-16', leapIdx: null, lengths: [30,29,29,30,29,29,30,29,30,30,30,29] },
  2000: { cny: '2000-02-05', leapIdx: null, lengths: [30,30,29,29,30,29,29,30,29,30,30,29] },
  2001: { cny: '2001-01-24', leapIdx: 3, lengths: [30,30,29,30,29,30,29,29,30,29,30,29,30] },
  2002: { cny: '2002-02-12', leapIdx: null, lengths: [30,30,29,30,29,30,29,29,30,29,30,29] },
  2003: { cny: '2003-02-01', leapIdx: null, lengths: [30,30,29,30,30,29,30,29,29,30,29,30] },
  2004: { cny: '2004-01-22', leapIdx: 1, lengths: [29,30,29,30,30,29,30,29,30,29,30,29,30] },
  2005: { cny: '2005-02-09', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,29,30,29] },
  2006: { cny: '2006-01-29', leapIdx: 6, lengths: [30,29,30,29,30,29,30,29,30,30,29,30,30] },
  2007: { cny: '2007-02-18', leapIdx: null, lengths: [29,29,30,29,29,30,29,30,30,30,29,30] },
  2008: { cny: '2008-02-07', leapIdx: null, lengths: [30,29,29,30,29,29,30,29,30,30,29,30] },
  2009: { cny: '2009-01-26', leapIdx: 4, lengths: [30,30,29,29,30,29,29,30,29,30,29,30,30] },
  2010: { cny: '2010-02-14', leapIdx: null, lengths: [30,29,30,29,30,29,29,30,29,30,29,30] },
  2011: { cny: '2011-02-03', leapIdx: null, lengths: [30,29,30,30,29,30,29,29,30,29,30,29] },
  2012: { cny: '2012-01-23', leapIdx: 3, lengths: [30,29,30,30,29,30,29,30,29,30,29,30,29] },
  2013: { cny: '2013-02-10', leapIdx: null, lengths: [30,29,30,29,30,30,29,30,29,30,29,30] },
  2014: { cny: '2014-01-31', leapIdx: 8, lengths: [29,30,29,30,29,30,29,30,30,29,30,29,30] },
  2015: { cny: '2015-02-19', leapIdx: null, lengths: [29,30,29,29,30,29,30,30,30,29,30,29] },
  2016: { cny: '2016-02-08', leapIdx: null, lengths: [30,29,30,29,29,30,29,30,30,29,30,30] },
  2017: { cny: '2017-01-28', leapIdx: 5, lengths: [29,30,29,30,29,29,30,29,30,29,30,30,30] },
  2018: { cny: '2018-02-16', leapIdx: null, lengths: [29,30,29,30,29,29,30,29,30,29,30,30] },
  2019: { cny: '2019-02-05', leapIdx: null, lengths: [30,29,30,29,30,29,29,30,29,29,30,30] },
  2020: { cny: '2020-01-25', leapIdx: 3, lengths: [29,30,30,30,29,30,29,29,30,29,30,29,30] },
  2021: { cny: '2021-02-12', leapIdx: null, lengths: [29,30,30,29,30,29,30,29,30,29,30,29] },
  2022: { cny: '2022-02-01', leapIdx: null, lengths: [30,29,30,29,30,30,29,30,29,30,29,30] },
  2023: { cny: '2023-01-22', leapIdx: 1, lengths: [29,30,29,29,30,30,29,30,30,29,30,29,30] },
  2024: { cny: '2024-02-10', leapIdx: null, lengths: [29,30,29,29,30,29,30,30,29,30,30,29] },
  2025: { cny: '2025-01-29', leapIdx: 5, lengths: [30,29,30,29,29,30,29,30,29,30,30,30,29] },
  2026: { cny: '2026-02-17', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,30,30,29] },
  2027: { cny: '2027-02-06', leapIdx: null, lengths: [30,30,29,30,29,29,30,29,29,30,30,29] },
  2028: { cny: '2028-01-26', leapIdx: 4, lengths: [30,30,30,29,30,29,29,30,29,29,30,30,29] },
  2029: { cny: '2029-02-13', leapIdx: null, lengths: [30,30,29,30,29,30,29,30,29,29,30,30] },
  2030: { cny: '2030-02-03', leapIdx: null, lengths: [29,30,29,30,30,29,30,29,30,29,30,29] },
  2031: { cny: '2031-01-23', leapIdx: 2, lengths: [29,30,30,29,30,29,30,30,29,30,29,30,29] },
  2032: { cny: '2032-02-11', leapIdx: null, lengths: [30,29,29,30,29,30,30,29,30,30,29,30] },
  2033: { cny: '2033-01-31', leapIdx: 10, lengths: [29,30,29,29,30,29,30,29,30,30,30,29,30] },
  2034: { cny: '2034-02-19', leapIdx: null, lengths: [29,30,29,29,30,29,30,29,30,30,29,30] },
  2035: { cny: '2035-02-08', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,30,29,30] },
  2036: { cny: '2036-01-28', leapIdx: 5, lengths: [30,30,29,30,29,29,30,29,29,30,29,30,30] },
  2037: { cny: '2037-02-15', leapIdx: null, lengths: [30,30,29,30,29,29,30,29,29,30,29,30] },
  2038: { cny: '2038-02-04', leapIdx: null, lengths: [30,30,29,30,29,30,29,30,29,29,30,29] },
  2039: { cny: '2039-01-24', leapIdx: 4, lengths: [30,30,29,30,30,29,30,29,30,29,30,29,29] },
  2040: { cny: '2040-02-12', leapIdx: null, lengths: [30,29,30,30,29,30,29,30,30,29,30,29] },
  2041: { cny: '2041-02-01', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,30,29,30] },
  2042: { cny: '2042-01-22', leapIdx: 1, lengths: [29,30,29,29,30,29,30,29,30,30,29,30,30] },
  2043: { cny: '2043-02-10', leapIdx: null, lengths: [29,30,29,29,30,29,29,30,30,29,30,30] },
  2044: { cny: '2044-01-30', leapIdx: 6, lengths: [30,29,30,29,29,30,29,29,30,29,30,30,30] },
  2045: { cny: '2045-02-17', leapIdx: null, lengths: [30,29,30,29,29,30,29,29,30,29,30,30] },
  2046: { cny: '2046-02-06', leapIdx: null, lengths: [30,29,30,29,30,29,30,29,29,30,29,30] },
  2047: { cny: '2047-01-26', leapIdx: 4, lengths: [30,29,30,30,29,30,29,30,29,29,30,29,30] },
  2048: { cny: '2048-02-14', leapIdx: null, lengths: [29,30,30,29,30,30,29,30,29,29,30,29] },
  2049: { cny: '2049-02-02', leapIdx: null, lengths: [30,29,30,29,30,30,29,30,30,29,30,29] },
  2050: { cny: '2050-01-23', leapIdx: 2, lengths: [29,30,29,30,29,30,29,30,30,29,30,30,29] },
  2051: { cny: '2051-02-11', leapIdx: null, lengths: [30,29,29,30,29,29,30,30,29,30,30,30] },
  2052: { cny: '2052-02-01', leapIdx: 7, lengths: [29,30,29,29,30,29,29,30,29,30,30,30,30] },
  2053: { cny: '2053-02-19', leapIdx: null, lengths: [29,30,29,29,30,29,29,30,29,30,30,30] },
  2054: { cny: '2054-02-08', leapIdx: null, lengths: [29,30,30,29,29,30,29,29,30,29,30,30] },
  2055: { cny: '2055-01-28', leapIdx: 5, lengths: [29,30,30,29,30,29,30,29,29,30,29,30,29] },
  2056: { cny: '2056-02-15', leapIdx: null, lengths: [30,30,30,29,30,29,30,29,29,30,29,30] },
  2057: { cny: '2057-02-04', leapIdx: null, lengths: [29,30,30,29,30,29,30,29,30,29,30,29] },
  2058: { cny: '2058-01-24', leapIdx: 3, lengths: [30,29,30,29,30,29,30,30,29,30,30,29,29] },
  2059: { cny: '2059-02-12', leapIdx: null, lengths: [30,29,30,29,30,29,30,29,30,30,30,29] },
  2060: { cny: '2060-02-02', leapIdx: null, lengths: [30,29,29,30,29,29,30,29,30,30,30,29] },
  2061: { cny: '2061-01-21', leapIdx: 2, lengths: [30,30,29,29,30,29,29,30,29,30,30,30,29] },
  2062: { cny: '2062-02-09', leapIdx: null, lengths: [30,30,29,29,30,29,29,30,29,30,30,29] },
  2063: { cny: '2063-01-29', leapIdx: 6, lengths: [30,30,29,30,29,30,29,29,30,29,30,29,30] },
  2064: { cny: '2064-02-17', leapIdx: null, lengths: [30,30,29,30,29,30,29,29,30,29,30,29] },
  2065: { cny: '2065-02-05', leapIdx: null, lengths: [30,30,29,30,30,29,30,29,29,30,29,30] },
  2066: { cny: '2066-01-26', leapIdx: 4, lengths: [29,30,29,30,30,29,30,29,30,29,30,29,30] },
  2067: { cny: '2067-02-14', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,29,30,29] },
  2068: { cny: '2068-02-03', leapIdx: null, lengths: [30,29,30,29,29,30,30,29,30,30,29,30] },
  2069: { cny: '2069-01-23', leapIdx: 3, lengths: [29,30,29,30,29,29,30,29,30,30,30,29,30] },
  2070: { cny: '2070-02-11', leapIdx: null, lengths: [29,30,29,30,29,29,30,29,30,30,29,30] },
  2071: { cny: '2071-01-31', leapIdx: 7, lengths: [30,29,30,29,30,29,29,30,29,30,29,30,30] },
  2072: { cny: '2072-02-19', leapIdx: null, lengths: [30,29,30,29,30,29,29,30,29,30,29,30] },
  2073: { cny: '2073-02-07', leapIdx: null, lengths: [30,29,30,30,29,30,29,29,30,29,30,29] },
  2074: { cny: '2074-01-27', leapIdx: 5, lengths: [30,29,30,30,29,30,29,30,29,30,29,30,29] },
  2075: { cny: '2075-02-15', leapIdx: null, lengths: [30,29,30,29,30,30,29,30,29,30,29,30] },
  2076: { cny: '2076-02-05', leapIdx: null, lengths: [29,30,29,30,29,30,29,30,30,29,30,29] },
  2077: { cny: '2077-01-24', leapIdx: 3, lengths: [30,29,30,29,29,30,29,30,30,30,29,30,29] },
  2078: { cny: '2078-02-12', leapIdx: null, lengths: [30,29,30,29,29,30,29,30,30,29,30,30] },
  2079: { cny: '2079-02-02', leapIdx: null, lengths: [29,30,29,30,29,29,30,29,30,29,30,30] },
  2080: { cny: '2080-01-22', leapIdx: 2, lengths: [30,29,30,29,30,29,29,30,29,29,30,30,30] },
  2081: { cny: '2081-02-09', leapIdx: null, lengths: [29,30,30,29,30,29,29,30,29,29,30,30] },
  2082: { cny: '2082-01-29', leapIdx: 6, lengths: [29,30,30,30,29,29,30,29,30,29,29,30,30] },
  2083: { cny: '2083-02-17', leapIdx: null, lengths: [29,30,30,29,30,29,30,29,30,29,30,29] },
  2084: { cny: '2084-02-06', leapIdx: null, lengths: [30,29,30,29,30,30,29,30,29,30,29,30] },
  2085: { cny: '2085-01-26', leapIdx: 4, lengths: [29,30,29,29,30,30,29,30,30,29,30,29,30] },
  2086: { cny: '2086-02-14', leapIdx: null, lengths: [29,30,29,29,30,29,30,30,29,30,30,29] },
  2087: { cny: '2087-02-03', leapIdx: null, lengths: [30,29,30,29,29,30,29,30,29,30,30,30] },
  2088: { cny: '2088-01-24', leapIdx: 3, lengths: [29,30,29,30,29,29,30,29,29,30,30,30,29] },
  2089: { cny: '2089-02-10', leapIdx: null, lengths: [30,30,29,30,29,29,29,30,29,30,30,29] },
  2090: { cny: '2090-01-30', leapIdx: 7, lengths: [30,30,30,29,30,29,29,30,29,29,30,30,29] },
  2091: { cny: '2091-02-18', leapIdx: null, lengths: [30,30,29,30,29,30,29,30,29,29,30,29] },
  2092: { cny: '2092-02-07', leapIdx: null, lengths: [30,30,29,30,30,29,30,29,30,29,30,29] },
  2093: { cny: '2093-01-27', leapIdx: 5, lengths: [29,30,30,29,30,29,30,30,29,30,29,30,29] },
  2094: { cny: '2094-02-15', leapIdx: null, lengths: [29,30,29,30,29,30,30,29,30,30,29,30] },
  2095: { cny: '2095-02-05', leapIdx: null, lengths: [29,30,29,29,30,29,30,29,30,30,30,29] },
  2096: { cny: '2096-01-25', leapIdx: 3, lengths: [30,29,30,29,29,30,29,29,30,30,30,29,30] },
  2097: { cny: '2097-02-12', leapIdx: null, lengths: [30,29,30,29,29,29,30,29,30,30,29,30] },
  2098: { cny: '2098-02-01', leapIdx: null, lengths: [30,30,29,30,29,29,29,30,29,30,29,30] },
  2099: { cny: '2099-01-21', leapIdx: 1, lengths: [30,30,29,30,30,29,29,30,29,29,30,29,30] },
};

// ── Lunar calendar names ─────────────────────────────────────
const LUNAR_MONTH = ["正","二","三","四","五","六","七","八","九","十","冬","腊"];
const LUNAR_DAY = ["初一","初二","初三","初四","初五","初六","初七","初八","初九","初十","十一","十二","十三","十四","十五","十六","十七","十八","十九","二十","廿一","廿二","廿三","廿四","廿五","廿六","廿七","廿八","廿九","三十"];

// ── solarToLunar: Convert solar date to lunar date ───────────
export interface LunarDate {
  lunarYear: number;
  lunarMonth: number;   // 1-12
  lunarDay: number;     // 1-30
  isLeap: boolean;
  monthName: string;    // e.g. "六" or "闰六"
  dayName: string;      // e.g. "初五"
}

export function solarToLunar(solarDate: string): LunarDate | null {
  const d = new Date(solarDate + "T00:00:00");
  if (isNaN(d.getTime())) return null;

  // Find the lunar year this date belongs to
  // A date belongs to lunar year Y if it is >= CNY of Y and < CNY of Y+1
  let lunarYear = d.getFullYear();

  // Check if date is before CNY of this solar year
  const thisYearData = LUNAR_DATA[lunarYear];
  if (thisYearData) {
    const cnyThis = new Date(thisYearData.cny + "T00:00:00");
    if (d < cnyThis) {
      lunarYear--;
    }
  }

  // Verify: check if date >= CNY of next year
  const nextYearData = LUNAR_DATA[lunarYear + 1];
  if (nextYearData) {
    const cnyNext = new Date(nextYearData.cny + "T00:00:00");
    if (d >= cnyNext) {
      lunarYear++;
    }
  }

  const data = LUNAR_DATA[lunarYear];
  if (!data) return null;

  // Iterate through months to find the right one
  const cny = new Date(data.cny + "T00:00:00");
  let cursor = new Date(cny);
  const totalMonths = data.lengths.length;

  for (let i = 0; i < totalMonths; i++) {
    const monthLen = data.lengths[i];
    const nextCursor = new Date(cursor);
    nextCursor.setDate(nextCursor.getDate() + monthLen);

    if (d >= cursor && d < nextCursor) {
      const dayOffset = Math.floor((d.getTime() - cursor.getTime()) / 86400000);
      const lunarDay = dayOffset + 1;

      // Determine month number and leap status
      // leapIdx points to the REGULAR month; leap month is at leapIdx+1
      let lunarMonth: number;
      let isLeap = false;

      if (data.leapIdx === null) {
        lunarMonth = i + 1;
      } else if (i === data.leapIdx + 1) {
        lunarMonth = data.leapIdx + 1;
        isLeap = true;
      } else if (i > data.leapIdx + 1) {
        lunarMonth = i;  // shift: leap month takes one slot
      } else {
        lunarMonth = i + 1;
      }

      const monthIdx = lunarMonth - 1;
      const monthName = isLeap ? `闰${LUNAR_MONTH[monthIdx]}` : LUNAR_MONTH[monthIdx];
      const dayName = LUNAR_DAY[lunarDay - 1] || String(lunarDay);

      return {
        lunarYear,
        lunarMonth,
        lunarDay,
        isLeap,
        monthName,
        dayName,
      };
    }

    cursor = nextCursor;
  }

  return null;
}

// ── lunarDate: Convert lunar date to solar date ──────────────
export function lunarDate(lunarYear: number, lunarMonth: number, lunarDay: number, isLeap = false): string {
  const data = LUNAR_DATA[lunarYear];
  if (!data) return "";

  // Calculate the target month index in the lengths array
  // leapIdx points to REGULAR month, leap month is at leapIdx+1
  let targetIdx: number;
  if (data.leapIdx === null) {
    targetIdx = lunarMonth - 1;
  } else if (isLeap && lunarMonth === data.leapIdx + 1) {
    targetIdx = data.leapIdx + 1;  // leap month is right after its regular counterpart
  } else if (lunarMonth > data.leapIdx + 1) {
    targetIdx = lunarMonth;  // months after leap shift by 1
  } else {
    targetIdx = lunarMonth - 1;
  }

  if (targetIdx < 0 || targetIdx >= data.lengths.length) return "";

  // Sum days from CNY to the target month start
  const cny = new Date(data.cny + "T00:00:00");
  let days = 0;
  for (let i = 0; i < targetIdx; i++) {
    days += data.lengths[i];
  }
  days += lunarDay - 1;

  const result = new Date(cny);
  result.setDate(result.getDate() + days);
  return fmtLocal(result);
}

// ── 清明节: 太阳黄经15° ──────────────────────────────────────
// Accurate algorithm instead of hardcoded table
function qingmingDate(year: number): string {
  // Qingming is around April 4-6 each year
  // Using the formula: 清明日期 = (Y*D+C)-L
  // Y = year % 100, D = 0.2422, C = 4.81 (for 20th century) or 5.59 (for 21st century)
  // L = Math.floor(Y/4)
  const Y = year % 100;
  const D = 0.2422;
  const C = year < 2000 ? 4.81 : (year < 2100 ? 5.59 : 5.59); // simplified
  const L = Math.floor(Y / 4);
  const day = Math.floor(Y * D + C) - L;
  return `${year}-04-${String(day).padStart(2, "0")}`;
}

// ── China Holidays (法定节假日 + 传统节日) ──
function cnHolidays(year: number): Holiday[] {
  const h: Holiday[] = [];

  h.push({ date: `${year}-01-01`, name: "元旦", emoji: "", type: "public" });

  // 春节 (正月初一 + 除夕 + 初二 + 初三)
  const sf = lunarDate(year, 1, 1);
  if (sf) {
    const eve = new Date(sf + "T00:00:00"); eve.setDate(eve.getDate() - 1);
    // Get correct lunar label for 除夕
    const eveLunar = solarToLunar(fmtLocal(eve));
    const eveLabel = eveLunar ? `${eveLunar.monthName}月${eveLunar.dayName}` : "腊月三十";
    h.push({ date: fmtLocal(eve), name: "除夕", emoji: "", type: "traditional", lunar: eveLabel });

    const d2 = new Date(sf + "T00:00:00"); d2.setDate(d2.getDate() + 1);
    const d3 = new Date(sf + "T00:00:00"); d3.setDate(d3.getDate() + 2);
    h.push({ date: sf, name: "春节", emoji: "", type: "public", lunar: "正月初一" });
    h.push({ date: fmtLocal(d2), name: "春节·初二", emoji: "", type: "public" });
    h.push({ date: fmtLocal(d3), name: "春节·初三", emoji: "", type: "public" });
  }

  // 元宵节 (正月十五)
  const yx = lunarDate(year, 1, 15);
  if (yx) h.push({ date: yx, name: "元宵节", emoji: "", type: "traditional", lunar: "正月十五" });

  // 清明节
  h.push({ date: qingmingDate(year), name: "清明节", emoji: "", type: "public" });

  // 劳动节
  h.push({ date: `${year}-05-01`, name: "劳动节", emoji: "", type: "public" });

  // 端午节 (五月初五)
  const db = lunarDate(year, 5, 5);
  if (db) h.push({ date: db, name: "端午节", emoji: "", type: "public", lunar: "五月初五" });

  // 七夕 (七月初七)
  const qx = lunarDate(year, 7, 7);
  if (qx) h.push({ date: qx, name: "七夕", emoji: "", type: "traditional", lunar: "七月初七" });

  // 中元节 (七月十五)
  const zy = lunarDate(year, 7, 15);
  if (zy) h.push({ date: zy, name: "中元节", emoji: "", type: "traditional", lunar: "七月十五" });

  // 中秋节 (八月十五)
  const ma = lunarDate(year, 8, 15);
  if (ma) h.push({ date: ma, name: "中秋节", emoji: "", type: "public", lunar: "八月十五" });

  // 重阳节 (九月初九)
  const cy = lunarDate(year, 9, 9);
  if (cy) h.push({ date: cy, name: "重阳节", emoji: "", type: "traditional", lunar: "九月初九" });

  // 国庆
  h.push({ date: `${year}-10-01`, name: "国庆节", emoji: "", type: "public" });
  h.push({ date: `${year}-10-02`, name: "国庆节·第2天", emoji: "", type: "public" });
  h.push({ date: `${year}-10-03`, name: "国庆节·第3天", emoji: "", type: "public" });

  // 腊八 (腊月初八)
  const lb = lunarDate(year, 12, 8);
  if (lb) h.push({ date: lb, name: "腊八节", emoji: "", type: "traditional", lunar: "腊月初八" });

  // 小年 (腊月廿三)
  const xn = lunarDate(year, 12, 23);
  if (xn) h.push({ date: xn, name: "小年", emoji: "", type: "traditional", lunar: "腊月廿三" });

  return h;
}

// ── Public API ────────────────────────────────────────────────
export function getHolidays(region: Region, year: number): Holiday[] {
  return region === "US" ? usHolidays(year) : cnHolidays(year);
}

export function getHolidaysForDate(region: Region, date: string): Holiday[] {
  const year = parseInt(date.slice(0, 4));
  return getHolidays(region, year).filter(h => h.date === date);
}

export function getHolidaysForRange(region: Region, start: string, end: string): Holiday[] {
  const sy = parseInt(start.slice(0, 4)), ey = parseInt(end.slice(0, 4));
  const all: Holiday[] = [];
  for (let y = sy; y <= ey; y++) all.push(...getHolidays(region, y));
  return all.filter(h => h.date >= start && h.date <= end);
}

// ── Event types ─────────────────────────────────────────────────
interface CalendarEvent {
  id: string;
  title: string;
  messageDescription?: string;
  start: string;         // ISO timestamp
  end?: string;          // ISO timestamp (null = point-in-time)
  allDay: boolean;
  location?: string;
  recurring?: {          // simple recurrence
    rule: "daily" | "weekly" | "monthly" | "yearly";
    interval: number;    // every N days/weeks/months/years
    until?: string;      // ISO end date
  };
  reminders: number[];   // minutes before event to remind
  tags: string[];
  created: string;
  updated: string;
}

// ── Storage ─────────────────────────────────────────────────────
function eventsPath(personDir: string) {
  return path.join(personDir, "calendar.json");
}

function loadEvents(personDir: string): CalendarEvent[] {
  try {
    return JSON.parse(fs.readFileSync(eventsPath(personDir), "utf8"));
  } catch (e) { console.error("[universe.infotech/local.mobile/apps/calendar/calendar.ts] " + ((e as any)?.message || e));
    return [];
  }
}

function saveEvents(personDir: string, events: CalendarEvent[]) {
  fs.writeFileSync(eventsPath(personDir), JSON.stringify(events, null, 2));
}

function genId(): string {
  return `ev-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

// ── Time helpers ────────────────────────────────────────────────
function today(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

function dayStart(date: string): Date {
  return new Date(date + "T00:00:00");
}

function dayEnd(date: string): Date {
  return new Date(date + "T23:59:59");
}

function eventsOnDay(events: CalendarEvent[], date: string): CalendarEvent[] {
  const start = dayStart(date);
  const end = dayEnd(date);
  return events.filter(e => {
    const eStart = new Date(e.start);
    const eEnd = e.end ? new Date(e.end) : eStart;
    return eStart <= end && eEnd >= start;
  }).sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime());
}

function upcomingEvents(events: CalendarEvent[], days = 7): CalendarEvent[] {
  const now = new Date();
  const cutoff = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);
  return events.filter(e => {
    const eStart = new Date(e.start);
    return eStart >= now && eStart <= cutoff;
  }).sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime());
}

// ── Render ──────────────────────────────────────────────────────
function formatTime(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" });
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("zh-CN", { month: "short", day: "numeric", weekday: "short" });
}

function formatDateShort(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("zh-CN", { month: "short", day: "numeric" });
}

function formatLunarDate(date: string): string {
  const lunar = solarToLunar(date);
  return lunar ? `农历${lunar.monthName}月${lunar.dayName}` : "";
}

function renderHoliday(h: Holiday): string {
  const lunarStr = h.lunar ? ` (${h.lunar})` : "";
  return `  ${h.emoji} **${h.name}**${lunarStr} — 节假日`;
}

function renderEvent(e: CalendarEvent, showDate = true): string {
  const timeStr = e.allDay
    ? "全天"
    : e.end
      ? `${formatTime(e.start)}–${formatTime(e.end)}`
      : formatTime(e.start);
  const dateStr = showDate ? `${formatDate(e.start)} ` : "";
  const descStr = e.messageDescription ? `\n    ${e.messageDescription.slice(0, 100)}` : "";
  const locStr = e.location ? ` · ${e.location}` : "";
  const recurStr = e.recurring ? ` · ${e.recurring.rule}` : "";
  const remindStr = (e.reminders && e.reminders.length > 0) ? ` · ${e.reminders.join(",")}min` : "";
  const tagsStr = (e.tags && e.tags.length > 0) ? ` · ${e.tags.join(",")}` : "";

  return `${dateStr}**${e.title}**\n   ${timeStr}${locStr}${recurStr}${remindStr}${tagsStr}${descStr}`;
}

function groupByMonth(holidays: Holiday[], region: Region): string {
  const grouped: Record<string, Holiday[]> = {};
  for (const h of holidays) {
    const m = h.date.slice(0, 7);
    (grouped[m] ??= []).push(h);
  }
  const lines: string[] = [];
  const regionLabel = region === "US" ? "美国" : "中国";
  lines.push(`**节假日日历 · ${regionLabel}**`);
  for (const [month, items] of Object.entries(grouped).sort()) {
    const d = new Date(month + "-01");
    const label = d.toLocaleDateString("zh-CN", { year: "numeric", month: "long" });
    lines.push(`\n**${label}**`);
    for (const h of items) {
      const day = parseInt(h.date.slice(8, 10));
      const wd = new Date(h.date + "T00:00:00").toLocaleDateString("zh-CN", { weekday: "short" });
      const lunarStr = h.lunar ? ` (${h.lunar})` : "";
      lines.push(`  ${h.emoji} ${day}日 ${wd} · **${h.name}**${lunarStr}`);
    }
  }
  return lines.join("\n");
}

// ── Main handler ───────────────────────────────────────────────
export async function calendarCmd(args: any, _ctx: any, personDir: string): Promise<any> {
  const events = loadEvents(personDir);
  const region = getRegion(personDir);

  // --add: create event
  if (args.add) {
    const title = typeof args.add === "string" ? args.add : args._?.[1];
    if (!title) return { content: [{ type: "text", text: "Usage: calendar --add <title> [--start <ISO>] [--end <ISO>] [--all-day] [--desc <text>] [--location <text>] [--remind <minutes>]" }] };

    const event: CalendarEvent = {
      id: genId(),
      title,
      messageDescription: args.desc as string | undefined,
      start: (args.start as string) || new Date().toISOString(),
      end: args.end as string | undefined,
      allDay: !!args["all-day"] || !!args.allDay,
      location: args.location as string | undefined,
      reminders: args.remind ? [parseInt(args.remind as string) || 15] : [15],
      tags: [],
      created: new Date().toISOString(),
      updated: new Date().toISOString(),
    };

    events.push(event);
    saveEvents(personDir, events);
    return { content: [{ type: "text", text: `Event created:\n${renderEvent(event)}` }] };
  }

  // --today: today's events + holidays
  if (args.today) {
    const td = today();
    const todaysEvents = eventsOnDay(events, td);
    const todaysHolidays = getHolidaysForDate(region, td);
    const lunarToday = formatLunarDate(td);
    const lines = [`**Today — ${formatDate(td)}**${lunarToday ? ` · ${lunarToday}` : ""}`];
    if (todaysHolidays.length > 0) {
      todaysHolidays.forEach(h => lines.push(renderHoliday(h)));
    }
    if (todaysEvents.length === 0 && todaysHolidays.length === 0) {
      lines.push("  No events today.");
    } else if (todaysEvents.length > 0) {
      lines.push(todaysHolidays.length > 0 ? "" : "");
      todaysEvents.forEach(e => lines.push(renderEvent(e, false)));
    }
    return { content: [{ type: "text", text: lines.join("\n") }] };
  }

  // --upcoming: next N days + holidays
  if (args.upcoming) {
    const days = parseInt(args.upcoming as string) || 7;
    const upcoming = upcomingEvents(events, days);
    const now = new Date();
    const cutoff = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);
    const upcomingHolidays = getHolidaysForRange(region, fmtLocal(now), fmtLocal(cutoff));
    const lines = [`**Upcoming (${days} days)**`];
    if (upcomingHolidays.length > 0) {
      upcomingHolidays.forEach(h => lines.push(`  ${h.emoji} ${formatDateShort(h.date)} · **${h.name}**${h.lunar ? ` (${h.lunar})` : ""}`));
      if (upcoming.length > 0) lines.push("");
    }
    if (upcoming.length === 0 && upcomingHolidays.length === 0) {
      lines.push("  No upcoming events.");
    } else {
      upcoming.forEach(e => lines.push(renderEvent(e)));
    }
    return { content: [{ type: "text", text: lines.join("\n") }] };
  }

  // --date <YYYY-MM-DD>: specific date + holidays
  if (args.date) {
    const date = args.date as string;
    const dayEvents = eventsOnDay(events, date);
    const dayHolidays = getHolidaysForDate(region, date);
    const lunarDate = formatLunarDate(date);
    const lines = [`**${formatDate(date + "T00:00:00")}**${lunarDate ? ` · ${lunarDate}` : ""}`];
    if (dayHolidays.length > 0) {
      dayHolidays.forEach(h => lines.push(renderHoliday(h)));
      if (dayEvents.length > 0) lines.push("");
    }
    if (dayEvents.length === 0 && dayHolidays.length === 0) {
      lines.push("  No events.");
    } else {
      dayEvents.forEach(e => lines.push(renderEvent(e, false)));
    }
    return { content: [{ type: "text", text: lines.join("\n") }] };
  }

  // --show <id>: detail
  if (args.show) {
    const id = args.show as string;
    const e = events.find(x => x.id === id);
    if (!e) return { content: [{ type: "text", text: `Event not found: ${id}` }] };
    return { content: [{ type: "text", text: renderEvent(e) + `\n  ID: \`${e.id}\`\n  Created: ${e.created.slice(0, 16)}` }] };
  }

  // --delete <id>
  if (args.delete) {
    const id = args.delete as string;
    const idx = events.findIndex(x => x.id === id);
    if (idx === -1) return { content: [{ type: "text", text: `Event not found: ${id}` }] };

    const title = events[idx].title;
    events.splice(idx, 1);
    saveEvents(personDir, events);
    return { content: [{ type: "text", text: `Deleted: **${title}**` }] };
  }

  // --search <q>: search events + holidays
  if (args.search) {
    const q = (args.search as string).toLowerCase();
    const results = events.filter(e =>
      e.title.toLowerCase().includes(q) ||
      (e.messageDescription && e.messageDescription.toLowerCase().includes(q)) ||
      (e.location && e.location.toLowerCase().includes(q)) ||
      (e.tags && e.tags.some((t: string) => t.toLowerCase().includes(q)))
    ).sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime());

    // Also search holidays
    const year = parseInt(today().slice(0, 4));
    const allHolidays = getHolidaysForRange(region, `${year}-01-01`, `${year + 1}-12-31`);
    const holidayResults = allHolidays.filter(h => h.name.toLowerCase().includes(q));

    if (results.length === 0 && holidayResults.length === 0) return { content: [{ type: "text", text: `No events matching "${args.search}".` }] };
    const total = results.length + holidayResults.length;
    const lines = [`**Search: "${args.search}" (${total})**`];
    if (holidayResults.length > 0) {
      holidayResults.forEach(h => lines.push(`  ${h.emoji} ${formatDateShort(h.date)} · **${h.name}**${h.lunar ? ` (${h.lunar})` : ""}`));
    }
    results.forEach(e => lines.push(renderEvent(e)));
    return { content: [{ type: "text", text: lines.join("\n") }] };
  }

  // --holidays: show all holidays for current region
  if (args.holidays) {
    const year = parseInt(args.holidays as string) || parseInt(today().slice(0, 4));
    const all = getHolidaysForRange(region, `${year}-01-01`, `${year}-12-31`);
    return { content: [{ type: "text", text: groupByMonth(all, region) }] };
  }

  // default: overview — today + upcoming + holidays
  const td = today();
  const todaysEvents = eventsOnDay(events, td);
  const todaysHolidays = getHolidaysForDate(region, td);
  const upcoming = upcomingEvents(events, 7);
  const regionLabel = region === "US" ? "美国" : "中国";

  const lines = [`**Calendar** — ${formatDate(td + "T00:00:00")} · ${regionLabel}`];

  // Today's holidays
  if (todaysHolidays.length > 0) {
    lines.push(`\n**今日节日:**`);
    todaysHolidays.forEach(h => lines.push(renderHoliday(h)));
  }

  // Today's events
  if (todaysEvents.length > 0) {
    lines.push(`\n**今日日程 (${todaysEvents.length}):**`);
    todaysEvents.forEach(e => lines.push(renderEvent(e, false)));
  } else if (todaysHolidays.length === 0) {
    lines.push("\n今日无日程");
  }

  // Upcoming holidays (next 7 days)
  const now = new Date();
  const cutoff = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  const upcomingHolidays = getHolidaysForRange(region, fmtLocal(now), fmtLocal(cutoff))
    .filter(h => h.date !== td);
  if (upcomingHolidays.length > 0) {
    lines.push(`\n**近期节日:**`);
    upcomingHolidays.forEach(h => lines.push(`  ${h.emoji} ${formatDateShort(h.date)} · **${h.name}**${h.lunar ? ` (${h.lunar})` : ""}`));
  }

  // Upcoming events
  if (upcoming.length > 0) {
    lines.push(`\n**未来7天日程:**`);
    upcoming.forEach(e => lines.push(renderEvent(e)));
  }

  lines.push(`\n操作: 今天 | 未来 | 日期 YYYY-MM-DD | 节日 | 搜索 <词> | 添加 <标题> | 详情 <id> | 删除 <id>`);
  return { content: [{ type: "text", text: lines.join("\n") }] };
}

export { type CalendarEvent, loadEvents, eventsOnDay, upcomingEvents };

// ── MobileApp wrapper ──────────────────────────────────────────
import type { MobileApp } from "../../system.kernel/kernel.ts";

export const app: MobileApp = {
  name: "calendar",
  icon: "日历",
  messageDescription: "日程管理、查询、提醒",

  onOpen(state, personDir) {
    const events = loadEvents(personDir);
    const region = getRegion(personDir);
    const regionLabel = region === "US" ? "美国" : "中国";
    const td = today();
    const todaysEvents = eventsOnDay(events, td);
    const todaysHolidays = getHolidaysForDate(region, td);
    const upcoming = upcomingEvents(events, 7);

    const lunarTodayStr = formatLunarDate(td);
    const lines = [
      "═══ 日历 ═══",
      "",
      `  今天: ${formatDate(td + "T00:00:00")}${lunarTodayStr ? ` · ${lunarTodayStr}` : ""}`,
      `  地区: ${regionLabel} (去设置切换)`,
      `  今日日程: ${todaysEvents.length} 件`,
      todaysHolidays.length > 0 ? `  今日节日: ${todaysHolidays.map(h => h.name).join(", ")}` : "",
      `  未来7天: ${upcoming.length} 件`,
      "",
      "  操作:",
      "    今天           — 查看今日日程+节日",
      "    未来           — 查看未来7天",
      "    日期 YYYY-MM-DD — 查看指定日期",
      "    节日 [年]     — 查看全年节假日",
      "    添加 <标题>   — 创建日程",
      "    搜索 <关键词> — 搜索日程和节日",
      "    详情 <id>     — 查看日程详情",
      "    删除 <id>     — 删除日程",
      "",
      "  返回 — 回主屏幕",
    ].filter(l => l !== "");
    return { screen: lines.join("\n"), state: state ?? {} };
  },

  async onAction(input, state, personDir) {
    const trimmed = input.trim();
    let args: any = {};

    if (/^(今天|today)$/i.test(trimmed)) {
      args = { today: true };
    } else if (/^(未来|upcoming)(\s+(\d+))?$/i.test(trimmed)) {
      const m = trimmed.match(/(\d+)/);
      args = { upcoming: m ? m[1] : "7" };
    } else if (/^日期\s+(\d{4}-\d{2}-\d{2})$/.test(trimmed)) {
      args = { date: trimmed.match(/(\d{4}-\d{2}-\d{2})/)![1] };
    } else if (/^节日(\s+(\d{4}))?$/.test(trimmed)) {
      const m = trimmed.match(/(\d{4})/);
      args = { holidays: m ? m[1] : String(new Date().getFullYear()) };
    } else if (/^(添加|add)\s+(.+)$/i.test(trimmed)) {
      const m = trimmed.match(/^(?:添加|add)\s+(.+)$/i)!;
      args = { add: m[1] };
    } else if (/^(搜索|search)\s+(.+)$/i.test(trimmed)) {
      const m = trimmed.match(/^(?:搜索|search)\s+(.+)$/i)!;
      args = { search: m[1] };
    } else if (/^(详情|show)\s+(.+)$/i.test(trimmed)) {
      const m = trimmed.match(/^(?:详情|show)\s+(.+)$/i)!;
      args = { show: m[1] };
    } else if (/^(删除|delete)\s+(.+)$/i.test(trimmed)) {
      const m = trimmed.match(/^(?:删除|delete)\s+(.+)$/i)!;
      args = { delete: m[1] };
    }
    // default: show overview

    const result = await calendarCmd(args, {}, personDir);
    return { screen: result.content[0].text, state: state ?? {} };
  },
};
